[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']
via_ir = true

[invariant]
fail_on_revert = true
runs = 1000
show_metrics = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
